name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Configure PortAudio
      run: |
        # Install PortAudio
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        PORTAUDIO_LIB="$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib"

        # Create lib directory and copy PortAudio
        mkdir -p lib
        cp -v "$PORTAUDIO_LIB" lib/
        chmod 755 lib/libportaudio.2.dylib

        # Fix library install name
        install_name_tool -id "@rpath/libportaudio.2.dylib" lib/libportaudio.2.dylib

        # Debug output
        echo "Library details:"
        otool -L lib/libportaudio.2.dylib

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 rubicon-objc py2app

        # Install PyAudio with system PortAudio
        export PORTAUDIO_PATH="$PWD/lib"
        export LDFLAGS="-L$PORTAUDIO_PATH"
        export CFLAGS="-I$(brew --prefix portaudio)/include"
        pip install --no-cache-dir pyaudio

        # Install remaining dependencies
        pip install -r requirements.txt

    - name: Build App
      run: |
        # Clean previous builds
        rm -rf dist build

        # Set library paths
        export DYLD_LIBRARY_PATH="$PWD/lib:$DYLD_LIBRARY_PATH"
        export LIBRARY_PATH="$PWD/lib:$LIBRARY_PATH"

        # Build with verbose output
        python setup.py py2app -vv

        # Debug output
        echo "App bundle contents:"
        ls -R dist/TalkToMe.app/Contents/
        echo "Library references in binary:"
        otool -L dist/TalkToMe.app/Contents/MacOS/TalkToMe

    - name: Create DMG
      run: |
        chmod +x create_dmg.sh
        ./create_dmg.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe-DMG
        path: TalkToMe.dmg
