name: Build Mac App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        brew install create-dmg
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app

    - name: Build App Bundle
      run: |
        chmod +x build_mac_app.sh create_dmg.sh
        ./build_mac_app.sh
        ./create_dmg.sh

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/TalkToMe.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
