name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Configure PortAudio
      run: |
        # Install PortAudio
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        PORTAUDIO_LIB="$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib"

        # Debug output
        echo "PortAudio prefix: $PORTAUDIO_PREFIX"
        echo "PortAudio library: $PORTAUDIO_LIB"
        ls -l "$PORTAUDIO_LIB"

        # Create lib directory and copy PortAudio
        mkdir -p lib
        cp -v "$PORTAUDIO_LIB" lib/
        chmod 755 lib/libportaudio.2.dylib

        # Debug library location
        echo "Copied PortAudio library:"
        ls -l lib/
        otool -L lib/libportaudio.2.dylib

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 rubicon-objc
        pip install --use-pep517 py2app

        # Set environment variables for PyAudio installation
        export PORTAUDIO_PATH="$PWD/lib"
        export DYLD_LIBRARY_PATH="$PORTAUDIO_PATH:$DYLD_LIBRARY_PATH"
        export LIBRARY_PATH="$PORTAUDIO_PATH:$LIBRARY_PATH"
        export CFLAGS="-I$(brew --prefix portaudio)/include"
        export LDFLAGS="-L$PORTAUDIO_PATH"

        # Install PyAudio with verbose output
        pip install --verbose --use-pep517 pyaudio

        # Install remaining dependencies
        pip install -r requirements.txt

    - name: Build App
      run: |
        rm -rf dist build

        # Debug environment
        echo "Current directory: $PWD"
        echo "PortAudio lib location:"
        ls -l lib/
        echo "Library path environment:"
        echo $DYLD_LIBRARY_PATH
        echo $DYLD_FALLBACK_LIBRARY_PATH

        # Build with verbose output
        python setup.py py2app -vv

        # Create frameworks directory in app bundle
        mkdir -p dist/TalkToMe.app/Contents/Frameworks

        # Copy PortAudio library with debug output
        echo "Copying PortAudio library..."
        cp -v lib/libportaudio.2.dylib dist/TalkToMe.app/Contents/Frameworks/
        chmod 755 dist/TalkToMe.app/Contents/Frameworks/libportaudio.2.dylib

        # Fix library references in app bundle with verbose output
        echo "Fixing library references..."
        find dist/TalkToMe.app -name "*.so" -o -name "*.dylib" | while read lib; do
          echo "Processing $lib"
          otool -L "$lib"
          chmod +w "$lib"
          install_name_tool -change "/usr/local/opt/portaudio/lib/libportaudio.2.dylib" \
            "@executable_path/../Frameworks/libportaudio.2.dylib" "$lib" || true
          install_name_tool -change "lib/libportaudio.2.dylib" \
            "@executable_path/../Frameworks/libportaudio.2.dylib" "$lib" || true
          echo "Finished processing $lib"
        done

        # Verify final library setup
        echo "Final library verification:"
        ls -lR dist/TalkToMe.app/Contents/Frameworks/
        otool -L dist/TalkToMe.app/Contents/Frameworks/libportaudio.2.dylib

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "TalkToMe" \
          --volicon "src/assets/AppIcon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "TalkToMe.app" 200 190 \
          --hide-extension "TalkToMe.app" \
          --app-drop-link 600 185 \
          "TalkToMe.dmg" \
          "dist/TalkToMe.app"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe
        path: TalkToMe.dmg
