name: Build Mac App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        brew install create-dmg
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app

    - name: Create App Icon
      run: |
        # Create temporary iconset directory
        mkdir AppIcon.iconset
        # Generate icon files
        sips -z 16 16     src/assets/AppIcon.png --out AppIcon.iconset/icon_16x16.png
        sips -z 32 32     src/assets/AppIcon.png --out AppIcon.iconset/icon_16x16@2x.png
        sips -z 32 32     src/assets/AppIcon.png --out AppIcon.iconset/icon_32x32.png
        sips -z 64 64     src/assets/AppIcon.png --out AppIcon.iconset/icon_32x32@2x.png
        sips -z 128 128   src/assets/AppIcon.png --out AppIcon.iconset/icon_128x128.png
        sips -z 256 256   src/assets/AppIcon.png --out AppIcon.iconset/icon_128x128@2x.png
        sips -z 256 256   src/assets/AppIcon.png --out AppIcon.iconset/icon_256x256.png
        sips -z 512 512   src/assets/AppIcon.png --out AppIcon.iconset/icon_256x256@2x.png
        sips -z 512 512   src/assets/AppIcon.png --out AppIcon.iconset/icon_512x512.png
        sips -z 1024 1024 src/assets/AppIcon.png --out AppIcon.iconset/icon_512x512@2x.png
        # Create icns file
        iconutil -c icns AppIcon.iconset
        mv AppIcon.icns src/assets/

    - name: Create DMG Background
      run: |
        # Create background image with installation instructions
        convert -size 800x400 xc:white \
          -font Helvetica -pointsize 14 \
          -draw "text 250,200 'Drag TalkToMe to Applications to install'" \
          -draw "line 300,180 550,180" \
          -draw "line 550,180 540,170" \
          -draw "line 550,180 540,190" \
          src/assets/background.png

    - name: Build App Bundle
      run: |
        chmod +x build_mac_app.sh create_dmg.sh
        ./build_mac_app.sh
        ./create_dmg.sh

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/TalkToMe.dmg
        body: |
          TalkToMe Voice-to-Text Application

          Installation:
          1. Download TalkToMe.dmg
          2. Open the DMG file
          3. Drag TalkToMe to your Applications folder
          4. Launch TalkToMe from Applications

          Features:
          - Voice-to-text with whisper support
          - System-wide text input
          - Support for quiet speech
          - Automatic permission handling
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
