name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PortAudio
      run: |
        brew install portaudio
        chmod +x prepare_framework.sh
        ./prepare_framework.sh
        otool -L PortAudio.framework/Versions/Current/PortAudio

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 rubicon-objc py2app

        # Install PyAudio with system PortAudio
        export DYLD_FRAMEWORK_PATH="$PWD:$DYLD_FRAMEWORK_PATH"
        export LIBRARY_PATH="$PWD/PortAudio.framework/Versions/Current:$LIBRARY_PATH"
        pip install --no-cache-dir pyaudio

        # Install remaining dependencies
        pip install -r requirements.txt

    - name: Build App
      run: |
        # Clean previous builds
        rm -rf dist build

        # Set framework path
        export DYLD_FRAMEWORK_PATH="$PWD:$DYLD_FRAMEWORK_PATH"

        # Build with verbose output
        python setup.py py2app -vv

        # Debug output
        echo "App bundle contents:"
        ls -R dist/TalkToMe.app/Contents/
        echo "Library references in binary:"
        otool -L dist/TalkToMe.app/Contents/MacOS/TalkToMe

    - name: Create DMG
      run: |
        chmod +x create_dmg.sh
        ./create_dmg.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe-DMG
        path: TalkToMe.dmg
