name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Configure PortAudio
      run: |
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        echo "PORTAUDIO_PATH=$PORTAUDIO_PREFIX" >> $GITHUB_ENV
        mkdir -p Frameworks/PortAudio.framework/Versions/A
        cp $PORTAUDIO_PREFIX/lib/libportaudio.2.dylib Frameworks/PortAudio.framework/Versions/A/PortAudio
        (cd Frameworks/PortAudio.framework && ln -sf Versions/A/PortAudio PortAudio)
        (cd Frameworks/PortAudio.framework/Versions && ln -sf A Current)
        echo "DYLD_FRAMEWORK_PATH=$PWD/Frameworks" >> $GITHUB_ENV
        echo "CFLAGS=-I$PORTAUDIO_PREFIX/include" >> $GITHUB_ENV
        echo "LDFLAGS=-L$PORTAUDIO_PREFIX/lib" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        PORTAUDIO_PATH=${{ env.PORTAUDIO_PATH }} pip install --use-pep517 pyaudio
        pip install -r requirements.txt
        pip install py2app --use-pep517

    - name: Build App
      run: |
        rm -rf dist build
        python setup.py py2app -vv
        mkdir -p dist/TalkToMe.app/Contents/Frameworks
        cp -R Frameworks/PortAudio.framework dist/TalkToMe.app/Contents/Frameworks/
        PYAUDIO_SO=$(find dist/TalkToMe.app -name "_portaudio.so")
        if [ -n "$PYAUDIO_SO" ]; then
          install_name_tool -change "${{ env.PORTAUDIO_PATH }}/lib/libportaudio.2.dylib" \
            "@rpath/PortAudio.framework/PortAudio" "$PYAUDIO_SO"
        fi
        install_name_tool -add_rpath "@executable_path/../Frameworks" \
          dist/TalkToMe.app/Contents/MacOS/TalkToMe

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "TalkToMe" \
          --volicon "src/assets/AppIcon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "TalkToMe.app" 200 190 \
          --hide-extension "TalkToMe.app" \
          --app-drop-link 600 185 \
          "TalkToMe.dmg" \
          "dist/TalkToMe.app"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe
        path: TalkToMe.dmg
