name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install py2app --use-pep517

    - name: Install and Configure PortAudio
      run: |
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        PORTAUDIO_LIB="$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib"
        mkdir -p lib
        cp "$PORTAUDIO_LIB" lib/
        chmod 755 lib/libportaudio.2.dylib
        echo "DYLD_LIBRARY_PATH=$PWD/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$PWD/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        otool -L lib/libportaudio.2.dylib

    - name: Build App
      run: |
        rm -rf dist build
        python setup.py py2app -vv
        mkdir -p dist/TalkToMe.app/Contents/Frameworks
        cp lib/libportaudio.2.dylib dist/TalkToMe.app/Contents/Frameworks/
        PYAUDIO_SO=$(find dist/TalkToMe.app -name "_portaudio.so")
        if [ -n "$PYAUDIO_SO" ]; then
          install_name_tool -change "@loader_path/libportaudio.2.dylib" "@rpath/libportaudio.2.dylib" "$PYAUDIO_SO"
          install_name_tool -change "/usr/local/lib/libportaudio.2.dylib" "@rpath/libportaudio.2.dylib" "$PYAUDIO_SO"
          install_name_tool -change "lib/libportaudio.2.dylib" "@rpath/libportaudio.2.dylib" "$PYAUDIO_SO"
          install_name_tool -id "@rpath/libportaudio.2.dylib" dist/TalkToMe.app/Contents/Frameworks/libportaudio.2.dylib
        fi
        install_name_tool -add_rpath "@executable_path/../Frameworks" dist/TalkToMe.app/Contents/MacOS/TalkToMe

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "TalkToMe" \
          --volicon "src/assets/AppIcon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "TalkToMe.app" 200 190 \
          --hide-extension "TalkToMe.app" \
          --app-drop-link 600 185 \
          "TalkToMe.dmg" \
          "dist/TalkToMe.app"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe
        path: TalkToMe.dmg
