name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Configure PortAudio
      run: |
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        PORTAUDIO_LIB="$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib"

        # Create framework structure
        FRAMEWORK_DIR="Frameworks"
        FRAMEWORK_NAME="libportaudio.2.dylib.framework"
        mkdir -p "$FRAMEWORK_DIR/$FRAMEWORK_NAME/Versions/A"
        cp "$PORTAUDIO_LIB" "$FRAMEWORK_DIR/$FRAMEWORK_NAME/Versions/A/"

        cd "$FRAMEWORK_DIR/$FRAMEWORK_NAME/Versions"
        ln -sf A Current
        cd ..
        ln -sf Versions/Current/libportaudio.2.dylib libportaudio.2.dylib
        cd ../..

        # Fix framework install name
        install_name_tool -id "@rpath/$FRAMEWORK_NAME/libportaudio.2.dylib" \
          "$FRAMEWORK_DIR/$FRAMEWORK_NAME/Versions/A/libportaudio.2.dylib"

        echo "PORTAUDIO_FRAMEWORK=$PWD/$FRAMEWORK_DIR/$FRAMEWORK_NAME" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 pyaudio
        pip install -r requirements.txt
        pip install py2app --use-pep517

    - name: Build App
      run: |
        rm -rf dist build

        # Build with verbose output
        python setup.py py2app -vv

        # Copy framework to app bundle
        mkdir -p dist/TalkToMe.app/Contents/Frameworks
        cp -R "$PORTAUDIO_FRAMEWORK" dist/TalkToMe.app/Contents/Frameworks/

        # Fix library references
        PYAUDIO_SO=$(find dist/TalkToMe.app -name "_portaudio.so")
        if [ -n "$PYAUDIO_SO" ]; then
          chmod +w "$PYAUDIO_SO"
          install_name_tool -change "@rpath/libportaudio.2.dylib" \
            "@rpath/$FRAMEWORK_NAME/libportaudio.2.dylib" "$PYAUDIO_SO"
          install_name_tool -add_rpath "@executable_path/../Frameworks" "$PYAUDIO_SO"
        fi

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "TalkToMe" \
          --volicon "src/assets/AppIcon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "TalkToMe.app" 200 190 \
          --hide-extension "TalkToMe.app" \
          --app-drop-link 600 185 \
          "TalkToMe.dmg" \
          "dist/TalkToMe.app"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe
        path: TalkToMe.dmg
