name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Configure PortAudio
      run: |
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        PORTAUDIO_LIB="$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib"

        # Verify and show PortAudio installation
        if [ ! -f "$PORTAUDIO_LIB" ]; then
          echo "Error: PortAudio library not found at $PORTAUDIO_LIB"
          exit 1
        fi

        # Show detailed library info
        echo "PortAudio library location: $PORTAUDIO_LIB"
        otool -L "$PORTAUDIO_LIB"

        # Export variables
        echo "PORTAUDIO_PATH=$PORTAUDIO_PREFIX" >> $GITHUB_ENV
        echo "PORTAUDIO_LIB=$PORTAUDIO_LIB" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$PORTAUDIO_PREFIX/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "DYLD_FRAMEWORK_PATH=$PORTAUDIO_PREFIX/lib:$DYLD_FRAMEWORK_PATH" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 pyaudio
        pip install -r requirements.txt
        pip install py2app --use-pep517

    - name: Build App
      run: |
        rm -rf dist build

        # Show environment
        echo "Current environment:"
        env | grep -i portaudio
        echo "Library location check:"
        ls -l "$PORTAUDIO_LIB"

        # Build with verbose output
        python setup.py py2app -vv

        # Create and populate Frameworks
        mkdir -p dist/TalkToMe.app/Contents/Frameworks
        cp "$PORTAUDIO_LIB" dist/TalkToMe.app/Contents/Frameworks/

        # Fix library references with verbose output
        echo "Fixing library references..."
        PYAUDIO_SO=$(find dist/TalkToMe.app -name "_portaudio.so")
        if [ -n "$PYAUDIO_SO" ]; then
          echo "Found PyAudio module at: $PYAUDIO_SO"
          chmod +w "$PYAUDIO_SO"

          echo "Current library references:"
          otool -L "$PYAUDIO_SO"

          echo "Updating library references..."
          install_name_tool -change "$PORTAUDIO_LIB" "@rpath/libportaudio.2.dylib" "$PYAUDIO_SO"
          install_name_tool -id "@rpath/libportaudio.2.dylib" dist/TalkToMe.app/Contents/Frameworks/libportaudio.2.dylib
          install_name_tool -add_rpath "@executable_path/../Frameworks" "$PYAUDIO_SO"

          echo "Updated library references:"
          otool -L "$PYAUDIO_SO"
        else
          echo "Error: PyAudio module not found!"
          exit 1
        fi

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "TalkToMe" \
          --volicon "src/assets/AppIcon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "TalkToMe.app" 200 190 \
          --hide-extension "TalkToMe.app" \
          --app-drop-link 600 185 \
          "TalkToMe.dmg" \
          "dist/TalkToMe.app"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe
        path: TalkToMe.dmg
