name: Build Mac App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        # Install dependencies
        brew install create-dmg
        brew install portaudio

        # Set up environment variables
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        echo "PORTAUDIO_PATH=$PORTAUDIO_PREFIX" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$PORTAUDIO_PREFIX/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$PORTAUDIO_PREFIX/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$PORTAUDIO_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

        # Create frameworks directory and copy PortAudio
        mkdir -p build/frameworks
        cp "$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib" build/frameworks/
        chmod +x build/frameworks/libportaudio.2.dylib

        # Fix library install name and verify
        install_name_tool -id "@rpath/libportaudio.2.dylib" build/frameworks/libportaudio.2.dylib
        otool -L build/frameworks/libportaudio.2.dylib

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --use-pep517 -r requirements.txt
        python -m pip install --use-pep517 py2app

    - name: Create App Assets
      run: |
        # Clean up any existing directories
        rm -rf src/assets
        mkdir -p src/assets

        # Create a white background for DMG using sips
        mkdir -p src/assets
        touch src/assets/background.png
        sips -s format png src/assets/background.png --out src/assets/background.png
        sips -z 400 800 src/assets/background.png
        sips -s format png -s formatOptions 100 src/assets/background.png

        # Use system app icon
        cp /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/GenericApplicationIcon.icns src/assets/AppIcon.icns

    - name: Build App
      run: |
        # Debug: Show PortAudio location
        ls -l build/frameworks/libportaudio.2.dylib
        otool -L build/frameworks/libportaudio.2.dylib

        # Build the app
        python setup.py py2app

    - name: Create DMG
      run: |
        chmod +x create_dmg.sh
        ./create_dmg.sh

    - name: Upload DMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TalkToMe-Installer
        path: dist/TalkToMe.dmg

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/TalkToMe.dmg
        name: "TalkToMe v${{ github.ref_name }}"
        prerelease: false
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: false
        body: |
          # TalkToMe Voice-to-Text Application

          ## Installation
          1. Download `TalkToMe.dmg` by clicking the file below
          2. Double-click the downloaded DMG file to open it
          3. When the installer window appears, drag the TalkToMe icon to the Applications folder
          4. Close the installer window
          5. Open TalkToMe from your Applications folder

          The application will automatically request necessary permissions when launched:
          - Microphone access (for voice recognition)
          - Accessibility access (for typing in any application)

          ## System Requirements
          - macOS 10.13 or later
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
