name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Configure PortAudio
      run: |
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        PORTAUDIO_LIB="$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib"

        # Debug PortAudio installation
        echo "PortAudio prefix: $PORTAUDIO_PREFIX"
        ls -l "$PORTAUDIO_PREFIX/lib"
        otool -L "$PORTAUDIO_LIB"

        # Create lib directory and copy PortAudio
        mkdir -p lib
        cp "$PORTAUDIO_LIB" lib/
        chmod 644 lib/libportaudio.2.dylib

        # Fix library install name and add rpath
        install_name_tool -id "@executable_path/../lib/libportaudio.2.dylib" lib/libportaudio.2.dylib

        # Set environment variables
        echo "PORTAUDIO_LIB=$PWD/lib/libportaudio.2.dylib" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$PWD/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 rubicon-objc
        pip install --use-pep517 py2app

        # Install PyAudio with PortAudio path
        export LDFLAGS="-L$PWD/lib"
        export CFLAGS="-I$(brew --prefix portaudio)/include"
        DYLD_LIBRARY_PATH=$PWD/lib pip install --use-pep517 pyaudio

        # Install remaining dependencies
        pip install -r requirements.txt

    - name: Build App
      run: |
        rm -rf dist build

        # Debug environment
        echo "Current directory: $PWD"
        echo "PortAudio lib location:"
        ls -l lib/
        echo "Library path environment:"
        echo $DYLD_LIBRARY_PATH

        # Show library info for debugging
        otool -L "$PORTAUDIO_LIB" || true
        otool -L lib/libportaudio.2.dylib || true

        # Build with verbose output and debug info
        DYLD_PRINT_LIBRARIES=1 DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 python setup.py py2app -vv

        # Fix library references in app bundle
        find dist/TalkToMe.app -name "*.so" -o -name "*.dylib" | while read lib; do
          echo "Checking $lib"
          otool -L "$lib"
          chmod +w "$lib"
          install_name_tool -change "@rpath/libportaudio.2.dylib" \
            "@executable_path/../lib/libportaudio.2.dylib" "$lib" || true
          install_name_tool -add_rpath "@executable_path/../lib" "$lib" || true
        done

        # Copy PortAudio library to app bundle and verify
        mkdir -p dist/TalkToMe.app/Contents/lib
        cp lib/libportaudio.2.dylib dist/TalkToMe.app/Contents/lib/
        ls -l dist/TalkToMe.app/Contents/lib/

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "TalkToMe" \
          --volicon "src/assets/AppIcon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "TalkToMe.app" 200 190 \
          --hide-extension "TalkToMe.app" \
          --app-drop-link 600 185 \
          "TalkToMe.dmg" \
          "dist/TalkToMe.app"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe
        path: TalkToMe.dmg
