name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        brew install portaudio
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build App
      run: |
        chmod +x build_mac_app.sh
        ./build_mac_app.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe-DMG
        path: TalkToMe.dmg
