name: Build Mac App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        # Install PortAudio and get its location
        brew install portaudio
        PORTAUDIO_PATH=$(brew --prefix portaudio)
        echo "PORTAUDIO_PATH=$PORTAUDIO_PATH" >> $GITHUB_ENV

        # Create audio plugins directory structure
        mkdir -p plugins/audio
        cp "$PORTAUDIO_PATH/lib/libportaudio.2.dylib" plugins/audio/
        chmod +x plugins/audio/libportaudio.2.dylib

        # Fix install name
        install_name_tool -id "@executable_path/../plugins/audio/libportaudio.2.dylib" plugins/audio/libportaudio.2.dylib

        # Verify plugin structure
        echo "Plugin structure:"
        ls -R plugins/
        echo "Library dependencies:"
        otool -L plugins/audio/libportaudio.2.dylib

    - name: Create App Assets
      run: |
        # Clean up and create directories
        rm -rf src/assets
        mkdir -p src/assets
        echo "Created assets directory"

        # Create white background using base64
        echo "iVBORw0KGgoAAAANSUhEUgAAAyAAAAGQAQAAAACle3N1AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAABJ0RVh0VGl0dGUAV2hpdGUgU3F1YXJlALjNkJYAAAATdEVYdEF1dGhvcgBEZXZpbiBBc3Npc3QC5YbmAAAAIXRFWHRDcmVhdGlvbiBUaW1lADIwMjQtMDEtMTFUMDA6NTk6MzlaJHJnAAAAHHRFWHRTb3VyY2UAaHR0cHM6Ly9pbmtzY2FwZS5vcmeb7jwaAAAAXUlEQVR42u3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOD1ACffAAF99yA0AAAAAElFTkSuQmCC" | base64 -d > src/assets/background.png
        echo "Created background image"

        # Use system app icon
        cp /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/GenericApplicationIcon.icns src/assets/AppIcon.icns
        echo "Created app icon"

        # Verify assets
        ls -l src/assets/

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --use-pep517 -r requirements.txt
        python -m pip install --use-pep517 py2app

        # Verify critical dependencies
        python -c "import pyaudio; print('PyAudio location:', pyaudio.__file__)"
        python -c "import whisper; print('Whisper location:', whisper.__file__)"
        python -c "import numpy; print('NumPy location:', numpy.__file__)"

        echo "Python dependencies installed successfully"

    - name: Build App
      run: |
        # Set environment variables
        export DYLD_LIBRARY_PATH="$PWD/plugins/audio:$DYLD_LIBRARY_PATH"
        export LIBRARY_PATH="$PWD/plugins/audio:$LIBRARY_PATH"

        # Clean previous builds
        rm -rf build dist

        # Build with verbose output
        python setup.py py2app -vv

        # Verify app bundle structure
        echo "App bundle contents:"
        ls -R dist/TalkToMe.app/Contents/
        echo "Frameworks in app bundle:"
        ls -la dist/TalkToMe.app/Contents/Frameworks/

    - name: Create DMG
      run: |
        chmod +x create_dmg.sh
        ./create_dmg.sh

    - name: Upload DMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TalkToMe-Installer
        path: dist/TalkToMe.dmg

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/TalkToMe.dmg
        name: "TalkToMe v${{ github.ref_name }}"
        prerelease: false
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: false
        body: |
          # TalkToMe Voice-to-Text Application

          ## Installation
          1. Download `TalkToMe.dmg` by clicking the file below
          2. Double-click the downloaded DMG file to open it
          3. When the installer window appears, drag the TalkToMe icon to the Applications folder
          4. Close the installer window
          5. Open TalkToMe from your Applications folder

          The application will automatically request necessary permissions when launched:
          - Microphone access (for voice recognition)
          - Accessibility access (for typing in any application)

          ## System Requirements
          - macOS 10.13 or later
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
