name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and Configure PortAudio
      run: |
        brew install portaudio
        PORTAUDIO_PREFIX=$(brew --prefix portaudio)
        PORTAUDIO_LIB="$PORTAUDIO_PREFIX/lib/libportaudio.2.dylib"

        # Create lib directory and copy PortAudio
        mkdir -p lib
        cp "$PORTAUDIO_LIB" lib/
        chmod 755 lib/libportaudio.2.dylib

        # Create framework structure
        mkdir -p lib/libportaudio.2.dylib.framework/Versions/A
        mv lib/libportaudio.2.dylib lib/libportaudio.2.dylib.framework/Versions/A/
        ln -s A lib/libportaudio.2.dylib.framework/Versions/Current
        ln -s Versions/Current/libportaudio.2.dylib lib/libportaudio.2.dylib.framework/libportaudio.2.dylib

        # Fix library install names
        install_name_tool -id "@rpath/libportaudio.2.dylib.framework/Versions/A/libportaudio.2.dylib" \
          lib/libportaudio.2.dylib.framework/Versions/A/libportaudio.2.dylib

        # Set environment variables for build
        echo "DYLD_LIBRARY_PATH=$PWD/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "DYLD_FRAMEWORK_PATH=$PWD/lib:$DYLD_FRAMEWORK_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$PWD/lib:$LIBRARY_PATH" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 rubicon-objc
        pip install --use-pep517 py2app

        # Install PyAudio with PortAudio path
        export LDFLAGS="-L$PWD/lib"
        export CFLAGS="-I$(brew --prefix portaudio)/include"
        DYLD_LIBRARY_PATH=$PWD/lib pip install --use-pep517 pyaudio

        # Install remaining dependencies
        pip install -r requirements.txt

    - name: Build App
      run: |
        rm -rf dist build

        # Debug environment
        echo "Current directory: $PWD"
        echo "PortAudio lib location:"
        ls -l lib/
        echo "Library path environment:"
        echo $DYLD_LIBRARY_PATH
        echo $DYLD_FALLBACK_LIBRARY_PATH

        # Build with verbose output
        python setup.py py2app -vv

        # Create frameworks directory in app bundle
        mkdir -p dist/TalkToMe.app/Contents/Frameworks

        # Copy framework structure
        cp -R lib/libportaudio.2.dylib.framework dist/TalkToMe.app/Contents/Frameworks/
        chmod -R 755 dist/TalkToMe.app/Contents/Frameworks/libportaudio.2.dylib.framework

        # Fix library references in app bundle
        find dist/TalkToMe.app -name "*.so" -o -name "*.dylib" | while read lib; do
          echo "Checking $lib"
          otool -L "$lib"
          chmod +w "$lib"
          install_name_tool -change "@rpath/libportaudio.2.dylib.framework/Versions/A/libportaudio.2.dylib" \
            "@executable_path/../Frameworks/libportaudio.2.dylib.framework/Versions/A/libportaudio.2.dylib" "$lib" || true
          install_name_tool -add_rpath "@executable_path/../Frameworks" "$lib" || true
        done

        # Verify final framework setup
        ls -lR dist/TalkToMe.app/Contents/Frameworks/
        otool -L dist/TalkToMe.app/Contents/Frameworks/libportaudio.2.dylib.framework/Versions/A/libportaudio.2.dylib

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "TalkToMe" \
          --volicon "src/assets/AppIcon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "TalkToMe.app" 200 190 \
          --hide-extension "TalkToMe.app" \
          --app-drop-link 600 185 \
          "TalkToMe.dmg" \
          "dist/TalkToMe.app"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe
        path: TalkToMe.dmg
