name: Build Mac App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        # Install PortAudio
        brew install portaudio

        # Prepare PortAudio framework
        chmod +x prepare_framework.sh
        ./prepare_framework.sh

        # Move framework to proper location
        mkdir -p dist/TalkToMe.app/Contents/Frameworks
        cp -R PortAudio.framework dist/TalkToMe.app/Contents/Frameworks/

        # Verify framework setup
        otool -L dist/TalkToMe.app/Contents/Frameworks/PortAudio.framework/Versions/Current/PortAudio

    - name: Create App Assets
      run: |
        # Clean up and create directories
        rm -rf src/assets
        mkdir -p src/assets
        echo "Created assets directory"

        # Create white background using base64
        echo "iVBORw0KGgoAAAANSUhEUgAAAyAAAAGQAQAAAACle3N1AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAABJ0RVh0VGl0dGUAV2hpdGUgU3F1YXJlALjNkJYAAAATdEVYdEF1dGhvcgBEZXZpbiBBc3Npc3QC5YbmAAAAIXRFWHRDcmVhdGlvbiBUaW1lADIwMjQtMDEtMTFUMDA6NTk6MzlaJHJnAAAAHHRFWHRTb3VyY2UAaHR0cHM6Ly9pbmtzY2FwZS5vcmeb7jwaAAAAXUlEQVR42u3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOD1ACffAAF99yA0AAAAAElFTkSuQmCC" | base64 -d > src/assets/background.png
        echo "Created background image"

        # Use system app icon
        cp /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/GenericApplicationIcon.icns src/assets/AppIcon.icns
        echo "Created app icon"

        # Verify assets
        ls -l src/assets/

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --use-pep517 -r requirements.txt
        python -m pip install --use-pep517 py2app

        # Verify PyAudio installation
        python -c "
        import pyaudio, os
        print('PyAudio:', pyaudio.__file__)
        print('Framework exists:', os.path.exists('dist/TalkToMe.app/Contents/Frameworks/PortAudio.framework'))
        "

    - name: Build App
      run: |
        # Clean previous builds if they exist
        rm -rf build

        # Set environment variables for build
        export DYLD_FRAMEWORK_PATH="$PWD/dist/TalkToMe.app/Contents/Frameworks:$DYLD_FRAMEWORK_PATH"
        export DYLD_LIBRARY_PATH="$PWD/dist/TalkToMe.app/Contents/Frameworks:$DYLD_LIBRARY_PATH"

        # Build with verbose output
        PYTHONPATH="$PWD" python setup.py py2app -vv

        # Fix PyAudio extension references
        PYAUDIO_SO=$(find dist/TalkToMe.app -name "_portaudio.so")
        if [ -n "$PYAUDIO_SO" ]; then
          install_name_tool -change "@rpath/libportaudio.2.dylib" \
            "@rpath/PortAudio.framework/Versions/Current/PortAudio" "$PYAUDIO_SO"
        fi

        # Verify app bundle
        echo "App bundle contents:"
        ls -R dist/TalkToMe.app/Contents/

    - name: Create DMG
      run: |
        chmod +x create_dmg.sh
        ./create_dmg.sh

    - name: Upload DMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TalkToMe-Installer
        path: dist/TalkToMe.dmg

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/TalkToMe.dmg
        name: "TalkToMe v${{ github.ref_name }}"
        prerelease: false
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: false
        body: |
          # TalkToMe Voice-to-Text Application

          ## Installation
          1. Download `TalkToMe.dmg` by clicking the file below
          2. Double-click the downloaded DMG file to open it
          3. When the installer window appears, drag the TalkToMe icon to the Applications folder
          4. Close the installer window
          5. Open TalkToMe from your Applications folder

          The application will automatically request necessary permissions when launched:
          - Microphone access (for voice recognition)
          - Accessibility access (for typing in any application)

          ## System Requirements
          - macOS 10.13 or later
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
