name: Build Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PortAudio
      run: |
        # Install PortAudio using Homebrew
        brew install portaudio

        # Create direct library link
        mkdir -p lib
        cp $(brew --prefix portaudio)/lib/libportaudio.2.dylib lib/
        chmod +x lib/libportaudio.2.dylib

        # Fix library install name
        install_name_tool -id "@executable_path/../Frameworks/libportaudio.2.dylib" lib/libportaudio.2.dylib

        # Debug output
        otool -L lib/libportaudio.2.dylib

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel

        # Install PyAudio with direct library path
        export LIBRARY_PATH="$PWD/lib:$LIBRARY_PATH"
        export DYLD_LIBRARY_PATH="$PWD/lib:$DYLD_LIBRARY_PATH"
        pip install --no-cache-dir pyaudio

        # Install remaining dependencies
        pip install --use-pep517 rubicon-objc py2app
        pip install -r requirements.txt

    - name: Build App
      run: |
        # Clean previous builds
        rm -rf dist build

        # Set library path for build
        export DYLD_LIBRARY_PATH="$PWD/lib:$DYLD_LIBRARY_PATH"
        export LIBRARY_PATH="$PWD/lib:$LIBRARY_PATH"

        # Build with verbose output
        python setup.py py2app -vv

        # Debug output
        echo "App bundle contents:"
        ls -R dist/TalkToMe.app/Contents/
        echo "Library references in binary:"
        otool -L dist/TalkToMe.app/Contents/MacOS/TalkToMe

    - name: Create DMG
      run: |
        chmod +x create_dmg.sh
        ./create_dmg.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TalkToMe-DMG
        path: TalkToMe.dmg
